Factory/Models/Engineer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Factory.Models
{
  public class Engineer
  {
    public int EngineerId { get; set; }
    [Required(ErrorMessage = "The Engineers's name can't be empty!")]
    public string EngineerName { get; set; }
    public List<EngineerMachine> JoinEntities { get; }
  }
}

Factory/Models/EngineerMachine.cs
namespace Factory.Models
{
  public class EngineerMachine
  {
    public int EngineerMachineId { get; set; }
    public int EngineerId { get; set; }
    public Engineer Engineer { get; set; }
    public int MachineId { get; set; }
    public Machine Machine { get; set; }
  }
}

Factory/Models/FactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
  public class FactoryContext: DbContext
  {
    public DbSet<Engineer> Engineers { get; set; }
    public DbSet<Machine> Machines { get; set; }
    public DbSet<EngineerMachine> EngineerMachines { get; set; }

    public FactoryContext(DbContextOptions options) : base (options) { }
  }
}

Factory/Models/Machine.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Factory.Models
{
  public class Machine
  {
    public int MachineId { get; set; }
    [Required(ErrorMessage = "The Machines's name can't be empty!")]
    public string MachineName { get; set; }
    public List<EngineerMachine> JoinEntities { get; }
  }
}

Factory/Controllers/EngineerController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq;
using System;


namespace Factory.Controllers
{
 public class EngineersController : Controller
  {
    private readonly FactoryContext _db;


    public EngineersController(FactoryContext db)
      {
        _db = db;
       }


    public ActionResult Index()
    {
       List<Engineer> model = _db.Engineers.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer)
    {
      if (!ModelState.IsValid)
      {
        return View(engineer);
      }
     else
      {
         _db.Engineers.Add(engineer);
         _db.SaveChanges();
         return RedirectToAction("Index");
      }
    }

    public ActionResult Details(int id)
    {
      Engineer thisEngineer = _db.Engineers
                            .Include(engineer => engineer.JoinEntities)
                            .ThenInclude(join => join.Machine)
                            .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Edit(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer)
    {
      if (!ModelState.IsValid)
      {
        return View(engineer);
      }
      else
      {
      _db.Engineers.Update(engineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
      }
    }

    public ActionResult Delete(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }  

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMachine(int id)
    {
      Engineer thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineName");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int machineId)
    {
      #nullable enable
      EngineerMachine? joinEntity = _db.EngineerMachines.FirstOrDefault(join => (join.MachineId == machineId && join.EngineerId == engineer.EngineerId));
      #nullable disable
      if (joinEntity == null && machineId != 0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() { MachineId = machineId, EngineerId = engineer.EngineerId});
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = engineer.EngineerId });
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      EngineerMachine joinEntry = _db.EngineerMachines.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachines.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
} 

Factory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Linq;


namespace Factory.Controllers
{
 public class HomeController : Controller
 {
   private readonly FactoryContext _db;

   public HomeController(FactoryContext db)
   {
     _db = db;
   }

   [HttpGet("/")]
   public ActionResult Index()
   {
     Engineer[] engineers = _db.Engineers.ToArray();
     Machine[] machines = _db.Machines.ToArray();
     Dictionary<string, object[]> model = new Dictionary<string, object[]>();
     model.Add("engineers", engineers);
     model.Add("machines", machines);
     return View(model);
   }
 }
}

Factory/Controllers/MachineController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq;
using System;


namespace Factory.Controllers
{
 public class MachinesController : Controller
  {
    private readonly FactoryContext _db;


    public MachinesController(FactoryContext db)
      {
        _db = db;
       }


    public ActionResult Index()
    {
       List<Machine> model = _db.Machines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      if (!ModelState.IsValid)
      {
        return View(machine);
      }
      else
      {
        _db.Machines.Add(machine);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public ActionResult Details(int id)
    {
      Machine thisMachine = _db.Machines
                            .Include(machine => machine.JoinEntities)
                            .ThenInclude(join => join.Engineer)
                            .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine)
    {
      if (!ModelState.IsValid)
      {
        return View(machine);
      }
      else
      {
      _db.Machines.Update(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
      }
    }

    public ActionResult Delete(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }  

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddEngineer(int id)
    {
      Machine thisMachine = _db.Machines.FirstOrDefault( machine => machine.MachineId == id);
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "EngineerName");
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult AddEngineer(Machine machine, int engineerId)
    {
      #nullable enable
      EngineerMachine? joinEntity = _db.EngineerMachines.FirstOrDefault(join => (join.EngineerId == engineerId && join.MachineId == machine.MachineId));
      #nullable disable
      if (joinEntity == null && engineerId != 0)
      {
        _db.EngineerMachines.Add(new EngineerMachine() { EngineerId = engineerId, MachineId = machine.MachineId});
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = machine.MachineId });
    }

    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      EngineerMachine joinEntry = _db.EngineerMachines.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachines.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Engineers/AddMachine.cshtml
@model Factory.Models.Engineer

<h2>Add a machine to @Model.EngineerName</h2>
<br>
<div class="list">
@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.EngineerId)

    @Html.Label("Select a Machine")
    @Html.DropDownList("MachineId")

    <input type="submit" value="Save" />
}
</div>
<br>

<div class="view-nav">
<button>@Html.ActionLink("Back to Engineer list", "Index")</button>
</div>

Factory/Views/Engineers/Create.cshtml
@model Factory.Models.Engineer

<h4>Add a new Engineer:</h4>
<br>
<div class="list">
<p>@Html.ValidationMessageFor(model => model.EngineerName, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.EngineerName)
  @Html.TextBoxFor(model => model.EngineerName)
  <input type="submit" value="add a new Engineer" />
}
</div>
<br>
<div class="view-nav">
<button>@Html.ActionLink("Show all Engineers", "Index")</button>
</div>

Factory/Views/Engineers/Delete.cshtml
@model Factory.Models.Engineer

<h2>Are you sure you want to delete @Model.EngineerName?<h2>
<br>
<h4>
@using (Html.BeginForm())
{
    <div style="text-align: center;">
    <input type="submit" value="Delete" />
    </div>
}
<br>
<br>
<div class="view-nav">
<button>@Html.ActionLink("Back to Engineer List", "Index")</button>
</h4>
<div class="view-nav">

Factory/Views/Engineers/Details.cshtml
@model Factory.Models.Engineer
@using Factory.Models;
@using System.Collections.Generic;


<h2>Engineer Details</h2>
<br>
<div class="list">
<h3>Engineer Name : @Model.EngineerName</h3>

@if (@Model.JoinEntities.Count == 0)
{
  <p>This Engineer does not work on any machines.</p>
}
else 
{
  <h4>This Engineers's current machines:</h4>
  <ul>
  @foreach (EngineerMachine join in Model.JoinEntities)
  {
    <li>@join.Machine.MachineName</li>

    @using (Html.BeginForm("DeleteJoin", "Engineers"))
      {
        @Html.Hidden("joinId", @join.EngineerMachineId)
        <input type="submit" value="Delete"/>
      }
  }
  </ul>
}
</div>
<br>

<div class="view-nav">
<button>@Html.ActionLink("Edit Engineer", "Edit", new { id = Model.EngineerId})</button>
<button>@Html.ActionLink("Delete Engineer", "Delete", new { id = Model.EngineerId}) </button>
<button>@Html.ActionLink("Back to engineer list", "Index")</button>
<button>@Html.ActionLink("Add Machine for this Engineer", "AddMachine", new { id = Model.EngineerId})</button>
</div>

Factory/Views/Engineers/Edit.cshtml
@model Factory.Models.Engineer

<h2>Edit Engineer</h2>
<br>
<div class="list">
<h4>Edit @Model.EngineerName</h4>

<p>@Html.ValidationMessageFor(model => model.EngineerName, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)

  @Html.LabelFor(model => model.EngineerName)
  @Html.EditorFor(model => model.EngineerName)

  <input type="submit" value="Save" />
}
</div>
<br>

<div class="view-nav">
<button>@Html.ActionLink("Back to Engineer list", "Index")</button>
</div>

Factory/Views/Engineers/Index.cshtml
@using Factory.Models;

<h2>Engineers</h2>
<p style="text-align: center;">Click an Engineer's name see their details!<p>

<div class="list">
<br>
@if (@Model.Count == 0)
{
  <h3>No engineers have been added yet!</h3>
}
else
{
  <ul>
  @foreach (Engineer engineer in Model)
  {
    <li>@Html.ActionLink($"{engineer.EngineerName}", "Details", new { id = engineer.EngineerId })</li>
  }
  </ul>
}
</div>
<br>

<div class="view-nav">
<button>@Html.ActionLink("Add new Engineer", "Create")</button>
</div>

Factory/Views/Home/Index.cshtml
@using Factory.Models;

<div class="card">
<br>
<h2>Engineers</h2>
@if (Model["engineers"].Length == 0)
{
  <p style="text-align: center;">No engineers have been added yet!</p>
}
<ul>
@foreach (Engineer engineer in Model["engineers"])
{
  <li style="text-align: center;">@Html.ActionLink(@engineer.EngineerName, "Details", "Engineers", new { id = @engineer.EngineerId})</li>
}
</ul>
</div>

<br>

<div class="card">
<br>
<h2>Machines</h2>
@if (Model["machines"].Length == 0)
{
  <p style="text-align: center;">No machines have been added yet!</p>
}
<ul>
@foreach (Machine machine in Model["machines"])
{
  <li style="text-align: center;">@Html.ActionLink(@machine.MachineName, "Details", "Machines", new { id = @machine.MachineId})</li>
}
</ul>
</div>

Factory/Views/Machines/AddEngineer.cshtml
@model Factory.Models.Machine

<h2>Add a show to @Model.MachineName</h2>
<br>
<div class="list">

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.MachineId)

    @Html.Label("Select a Engineer")
    @Html.DropDownList("EngineerId")

    <input type="submit" value="Save" />
}
</div>
<br>

<div class="view-nav">
<button>@Html.ActionLink("Back to Machine list", "Index")</button>
</div>

Factory/Views/Machines/Create.cshtml
@model Factory.Models.Machine

<h4>Add a new Machine:</h4>
<br>
<div class="list">
<p>@Html.ValidationMessageFor(model => model.MachineName, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.MachineName)
  @Html.TextBoxFor(model => model.MachineName)
  <input type="submit" value="add a new Machine" />

}
</div>
<br>

<div class="view-nav">
<button>@Html.ActionLink("Show all Machines", "Index")</button>
</div>

Factory/Views/Machines/Delete.cshtml
@model Factory.Models.Machine

<h2>Are you sure you want to delete @Model.MachineName?<h2>
<br>
<h4>
@using (Html.BeginForm())
{
    <div style="text-align: center;">
    <input type="submit" value="Delete" />
    </div>
}
<br>
<br>

<div class="view-nav">
<button>@Html.ActionLink("Back to Machine List", "Index")</button>
</h4>
</div>

Factory/Views/Machines/Details.cshtml
@model Factory.Models.Machine
@using Factory.Models;
@using System.Collections.Generic;


<h2>Machine Details</h2>

<br>
<div class="list">
<h3>Machine Name : @Model.MachineName</h3>

@if (@Model.JoinEntities.Count == 0)
{
  <p>This Machine does not have any Engineers working on it.</p>
}
else 
{
  <h4>This Machines's current engineers:</h4>
  <ul>
  @foreach (EngineerMachine join in Model.JoinEntities)
  {
    <li>@join.Engineer.EngineerName</li>

      @using (Html.BeginForm("DeleteJoin", "Machines"))
      {
        @Html.Hidden("joinId", @join.EngineerMachineId)
        <input type="submit" value="Delete"/>
      }
  }
  </ul>
}

</div>
<br>

<div class="view-nav">
<button>@Html.ActionLink("Edit Machine", "Edit", new { id = Model.MachineId})</button>
<button>@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId}) </button>
<button>@Html.ActionLink("Back to Machine list", "Index")</button>
<button>@Html.ActionLink("Add Engineer for this Machine", "AddEngineer", new { id = Model.MachineId})</button>
</div>

Factory/Views/Machines/Edit.cshtml
@model Factory.Models.Machine

<h2>Edit Machine</h2>
<br>
<div class="list">
<h4>Edit @Model.MachineName</h4>

<p>@Html.ValidationMessageFor(model => model.MachineName, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.LabelFor(model => model.MachineName)
  @Html.EditorFor(model => model.MachineName)

  <input type="submit" value="Save" />
}
</div>
<br>
<div class="view-nav">
<button>@Html.ActionLink("Back to Machine list", "Index")</button>
</div>

Factory/Views/Machines/Index.cshtml
@using Factory.Models;

<h2>Machines</h2>
<p style="text-align: center;">Click an Machines's name see it's details!<p>

<div class="list">
<br>
@if (@Model.Count == 0)
{
  <h4>No machines have been added yet!</h4>
}
else
{
  <ul>
  @foreach (Machine machine in Model)
  {
    <li>@Html.ActionLink($"{machine.MachineName}", "Details", new { id = machine.MachineId })</li>
  }
  </ul>
}
</div>
<br>

<div class="view-nav">
<button>@Html.ActionLink("Add new Machine", "Create")</button>
</div>

Factory/Views/Shared/_Header.cshtml
<div id="header">
<div id="header-text">
  <h1>Dr.SillyStringz Factory</h1>
  <h4><em>Where being <strong>silly</strong> is is <strong>serious</strong> business!</em><h4>
  </div>
  <div id="header-navigation">
    <button>@Html.ActionLink("Home", "Index", "Home")</button>
    <button>@Html.ActionLink("Engineers", "Index", "Engineers")</button>
    <button>@Html.ActionLink("Machines", "Index", "Machines")</button>
  </div>
  <br />
</div>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>@ViewBag.PageTitle</title>
    <link 
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" 
      rel="stylesheet" 
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" 
      crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @await Html.PartialAsync("_Header")
    <br>
    <br>
    @RenderBody()
  </body>
</html>